### PR TITLE
Fixed issue #41 where redirect_uris couldn't be passed in as a hash

### PR DESCRIPTION
**Pull request by joncalhoun**

### CODE REVIEW

**Comment by joncalhoun** [comment]
Any update on this? The PR has been open for 2 weeks now with no response :(

**Comment by sqrrrl** [comment]
Really don't want to get further into the habit of accepting params in multiple formats. Much rather fix the serialization to JSON to write the URL out as a string instead.

**Comment by joncalhoun** [comment]
I can understand that. Is the intent to continue supporting this behavior in oauth_1 then? I ask because it appears to do this in at least 2 places where URIs are set.

I had created this PR because the last time I attempted to use the [google-api-ruby-client](https://github.com/google/google-api-ruby-client) with the calendar API this caused some things to break. Ideally this would be fixed sooner rather than later so developers can utilize the library, so I suppose some options would be:

1. Temporarily support this until the other lib gets updated. This may be annoying if other libraries using signet start to utilize it and break in the future though.

2. Update the [google-api-ruby-client](https://github.com/google/google-api-ruby-client). I don't know the scope of this, so if you have any idea the feedback would be great.

3. Something I am missing. Any other ideas?

I'm happy to help with this, but I will need some guidance on how to proceed. Thanks! :smiley:

**Comment by sqrrrl** [comment]
FWIW, in the process of updating google-api-ruby-client and google-auth-library-ruby for better 3-legged OAuth2 support. First part was already committed and web support is coming shortly. Those enhancements better define token storage and exclude writing fields like the URLs since they're config, not user data. In other words, it won't suffer this problem.

Keep an on google-auth-library-ruby for the rest of the changes over the next couple of weeks.

**Comment by joncalhoun** [comment]
Awesome, thanks for the update :)

**Pull request closed without merging**
