### PR TITLE
Handle 5xx errors with RemoteServerError

### PR DESCRIPTION
**Pull request by ylecuyer**
Currently 5xx errors return a Signet::AuthorizationError which is misleading

I added a Signet::RemoteServerError so they can be distinguished

### CODE REVIEW

**Comment by ylecuyer** [comment]
I did it

**Comment by ylecuyer** [comment]
@dazuma are you still the one in charge of the repo ?

**Comment by ylecuyer** [comment]
ping @sqrrrl, please someone ?

**Comment by jiop** [comment]
Is there any update on this PR?

**Pull request merged**
